// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_chat_gpt/hive_model/chat_item_model.dart';
import 'package:flutter_chat_gpt/hive_model/message_item_model.dart';
import 'package:flutter_chat_gpt/hive_model/message_role_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChatItemModelAdapter());
    registerAdapter(MessageItemModelAdapter());
    registerAdapter(MessageRoleModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChatItemModelAdapter());
    registerAdapter(MessageItemModelAdapter());
    registerAdapter(MessageRoleModelAdapter());
  }
}
